export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <h1>This is admin dashboard</h1>
      <body>{children}</body>
    </html>
  )
}
